#ifndef ERRORS_H
#define ERRORS_H

typedef enum {
    NONE_ERROR,
    MEMORY_ALLOCATION_ERROR,
    SERVER_CREAT_FAILED_ERROR,
    INVALID_SERVER_CONFIG_ERROR,
    SERVER_INIT_FAILED_ERROR,
    PAGE_NOT_FOUND_ERROR,
    FILE_NOT_FOUND_ERROR,
    FILE_READ_ERROR,
    INVALID_API_REQUEST_ERROR,
    INVALID_API_PARAMETERS_ERROR,
    ERRORS_COUNT,
} ErrorCode;

extern const char* errorsMessages[ERRORS_COUNT];
extern const int errorsHttpCodes[ERRORS_COUNT];

#endif
